import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import { usePolling } from "../hooks/usePolling";
import { SeverityBadge, IncidentStatusBadge, OrderStatusBadge } from "../components/StatusBadge";

export function IncidentDetail() {
  const { id } = useParams<{ id: string }>();
  const incidentId = Number(id);
  const { data: incident, error } = usePolling(() => api.getIncident(incidentId), 4000, [incidentId]);
  const [busy, setBusy] = useState<"investigate" | "resolve" | null>(null);

  async function handleInvestigate() {
    setBusy("investigate");
    try {
      await api.investigateIncident(incidentId);
    } finally {
      setBusy(null);
    }
  }

  async function handleResolve() {
    setBusy("resolve");
    try {
      await api.resolveIncident(incidentId);
    } finally {
      setBusy(null);
    }
  }

  if (error) return <div className="error-banner">Failed to load incident: {error}</div>;
  if (!incident) return null;

  const latestReport = incident.reports[0];

  return (
    <div>
      <Link to="/incidents" className="back-link">
        &larr; All incidents
      </Link>

      <div className="section-header">
        <div>
          <h1>{incident.title}</h1>
          <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
            <SeverityBadge severity={incident.severity} />
            <IncidentStatusBadge status={incident.status} />
          </div>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="button secondary" onClick={handleInvestigate} disabled={busy !== null || incident.status === "INVESTIGATING"}>
            {incident.status === "INVESTIGATING" ? "Investigating…" : latestReport ? "Re-investigate" : "Investigate"}
          </button>
          {incident.status !== "RESOLVED" && (
            <button className="button" onClick={handleResolve} disabled={busy !== null}>
              Mark resolved
            </button>
          )}
        </div>
      </div>

      <div className="card">
        <h2>Detector summary</h2>
        <p style={{ fontSize: 13, color: "var(--text-secondary)", margin: 0 }}>{incident.summary}</p>
      </div>

      {latestReport ? (
        <div className="card">
          <h2>Root cause{latestReport.status === "FAILED" ? " — investigation failed" : ""}</h2>
          {latestReport.status === "FAILED" ? (
            <p style={{ fontSize: 13, color: "var(--status-critical)" }}>{latestReport.errorMessage}</p>
          ) : (
            <>
              <p style={{ fontSize: 14 }}>{latestReport.rootCause}</p>
              <p className="stat-tile-hint">
                Confidence: <strong>{latestReport.confidence}</strong> &middot; generated by {latestReport.model} at{" "}
                {new Date(latestReport.generatedAt).toLocaleString()}
              </p>

              <h2 style={{ marginTop: 20 }}>Investigation trail</h2>
              <ul className="evidence-list">
                {latestReport.evidenceTrail.map((step) => (
                  <li className="evidence-item" key={step.step}>
                    <span className="evidence-step">{step.step}</span>
                    <span>{step.finding}</span>
                  </li>
                ))}
              </ul>

              <h2 style={{ marginTop: 20 }}>Recommended actions</h2>
              <ul className="recommend-list">
                {latestReport.recommendedActions.map((action, i) => (
                  <li key={i}>{action}</li>
                ))}
              </ul>
            </>
          )}
        </div>
      ) : (
        <div className="card empty-state">
          No report yet. {incident.status === "INVESTIGATING" ? "The agent is investigating…" : 'Click "Investigate" to run the agent.'}
        </div>
      )}

      <div className="card">
        <h2>Related orders ({incident.relatedOrders?.length ?? 0})</h2>
        {incident.relatedOrders && incident.relatedOrders.length > 0 ? (
          <table>
            <thead>
              <tr>
                <th>Seq #</th>
                <th>External ID</th>
                <th>Status</th>
                <th>Currency</th>
                <th>Attempts</th>
                <th>Last error</th>
              </tr>
            </thead>
            <tbody>
              {incident.relatedOrders.map((order) => (
                <tr key={order.id}>
                  <td className="mono">#{order.sequenceNumber}</td>
                  <td className="mono">{order.externalId}</td>
                  <td>
                    <OrderStatusBadge status={order.status} />
                  </td>
                  <td>{order.currency}</td>
                  <td>{order.attemptCount}</td>
                  <td style={{ color: "var(--text-secondary)" }}>{order.lastError ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="empty-state">No related orders.</div>
        )}
      </div>
    </div>
  );
}
